CC=gcc
CFLAGS=-Wall -Wextra

all: part13_c part13_s

part13_c: part13_c.c
		$(CC) $(CFLAGS) -o part13_c part13_c.c

part13_s: part13_s.c
		$(CC) $(CFLAGS) -o part13_s part13_s.c

clean:
		rm -f part13_c part13_s