CC = gcc
CFLAGS = -Wall -g

all: part1 part2 part3

part1: part1.c
		$(CC) $(CFLAGS) -o part1 part1.c

part2: part2.c
		$(CC) $(CFLAGS) -o part2 part2.c

part3: part3.c
		$(CC) $(CFLAGS) -o part3 part3.c

clear:
		rm -f part1 part2 part3